package com.liskovsoft.smartyoutubetv2.common.exoplayer.other;

import com.google.android.exoplayer2.Format;
import com.google.android.exoplayer2.util.MimeTypes;
import com.liskovsoft.mediaserviceinterfaces.data.MediaSubtitle;
import com.liskovsoft.smartyoutubetv2.common.exoplayer.selector.TrackSelectorManager;
import com.liskovsoft.smartyoutubetv2.common.exoplayer.selector.track.MediaTrack;

import org.junit.Test;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

/**
 * T02 acceptance: the selected subtitle track is bound to exactly one source, and every ambiguous or
 * unknown case is refused instead of falling back to the first candidate.
 */
public class SubtitleSourceBinderTest {
    private static final String ORIGIN_URL = "https://example.com/api/timedtext?v=abc&lang=en&fmt=srv3";
    private static final String TRANSLATED_URL = ORIGIN_URL + "&tlang=zh-Hans";
    private static final String ASR_URL = "https://example.com/api/timedtext?v=abc&lang=en&kind=asr&fmt=srv3";

    private static MediaSubtitle subtitle(String vssId, String languageCode, String name, String url) {
        return new MediaSubtitle() {
            @Override
            public String getBaseUrl() {
                return url;
            }

            @Override
            public boolean isTranslatable() {
                return true;
            }

            @Override
            public String getLanguageCode() {
                return languageCode;
            }

            @Override
            public String getVssId() {
                return vssId;
            }

            @Override
            public String getName() {
                return name;
            }

            @Override
            public String getMimeType() {
                return MimeTypes.APPLICATION_MP4VTT;
            }

            @Override
            public String getCodecs() {
                return null;
            }

            @Override
            public String getType() {
                return null;
            }
        };
    }

    private static Format format(String vssId, String name) {
        return Format.createTextSampleFormat(vssId, MimeTypes.APPLICATION_MP4VTT, 0, name);
    }

    @Test
    public void bindsEachRepresentationToItsOwnSourceWhenVssIdAndNameAreShared() {
        // A derived YouTube translation track reuses the origin vssId; only its URL differs.
        Format originFormat = format("en", "English");
        Format derivedFormat = format("en", "English");
        List<MediaSubtitle> subtitles = Arrays.asList(subtitle("en", "en", "English", ORIGIN_URL),
                subtitle("en", "zh-Hans", "English", TRANSLATED_URL));
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        binder.bind(subtitles, Arrays.asList(new SubtitleFormatCandidate(originFormat, ORIGIN_URL),
                new SubtitleFormatCandidate(derivedFormat, TRANSLATED_URL)));

        SelectedSubtitleSource origin = binder.resolve(originFormat);
        assertNotNull(origin);
        assertEquals("en", origin.getLanguageCode());
        assertEquals(ORIGIN_URL, origin.getBaseUrl());

        SelectedSubtitleSource derived = binder.resolve(derivedFormat);
        assertNotNull(derived);
        assertEquals("zh-Hans", derived.getLanguageCode());
        assertEquals(TRANSLATED_URL, derived.getBaseUrl());
        assertEquals(SubtitleSourceBinder.Status.BOUND, binder.getStatus());
        assertEquals(2, binder.getBoundCount());
    }

    @Test
    public void keepsManualAndAutoGeneratedTracksWithTheSameNameDistinct() {
        Format manualFormat = format("en", "English");
        Format asrFormat = format("a.en", "English");
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        binder.bind(Arrays.asList(subtitle("en", "en", "English", ORIGIN_URL),
                        subtitle("a.en", "en", "English", ASR_URL)),
                Arrays.asList(new SubtitleFormatCandidate(manualFormat, ORIGIN_URL),
                        new SubtitleFormatCandidate(asrFormat, ASR_URL)));

        assertEquals("en", binder.resolve(manualFormat).getVssId());
        assertEquals("a.en", binder.resolve(asrFormat).getVssId());
    }

    @Test
    public void equivalentDuplicateMetadataDoesNotMakeTheSourceAmbiguous() {
        Format format = format("en", "English");
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        binder.bind(Arrays.asList(subtitle("en", "en", "English", ORIGIN_URL),
                        subtitle("en", "en", "English duplicate", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(format, ORIGIN_URL)));

        assertNotNull(binder.resolve(format));
        assertEquals(SubtitleSourceBinder.Status.BOUND, binder.getStatus());
        assertEquals(1, binder.getBoundCount());
        assertEquals(0, binder.getRejectedCount());
    }

    @Test
    public void conflictingLanguagesAtOneUrlRemainAmbiguous() {
        Format format = format("en", "English");
        SubtitleSourceBinder binder = new SubtitleSourceBinder();
        binder.bind(Arrays.asList(subtitle("en", "en", "English", ORIGIN_URL),
                        subtitle("en", "fr", "French", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(format, ORIGIN_URL)));
        assertNull(binder.resolve(format));
        assertEquals(SubtitleSourceBinder.Status.SOURCE_AMBIGUOUS, binder.getStatus());
    }

    @Test
    public void reportsUnknownWhenNoSourceEntryMatchesTheRepresentation() {
        Format format = format("en", "English");
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        binder.bind(Collections.singletonList(subtitle("en", "en", "English", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(format, TRANSLATED_URL)));

        assertNull(binder.resolve(format));
        assertEquals(SubtitleSourceBinder.Status.SOURCE_UNKNOWN, binder.getStatus());
    }

    @Test
    public void reportsNotSelectedForAnEmptyOrMissingTrack() {
        SubtitleSourceBinder binder = new SubtitleSourceBinder();
        binder.bind(Collections.singletonList(subtitle("en", "en", "English", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(format("en", "English"), ORIGIN_URL)));

        assertNull(binder.resolve(MediaTrack.forRendererIndex(TrackSelectorManager.RENDERER_INDEX_SUBTITLE)));
        assertEquals(SubtitleSourceBinder.Status.NOT_SELECTED, binder.getStatus());

        assertNull(binder.resolve((Format) null));
        assertEquals(SubtitleSourceBinder.Status.NOT_SELECTED, binder.getStatus());
    }

    @Test
    public void resolvesTheTrackByFormatIdentity() {
        Format format = format("en", "English");
        MediaTrack track = MediaTrack.forRendererIndex(TrackSelectorManager.RENDERER_INDEX_SUBTITLE);
        track.format = format;
        track.groupIndex = 3;
        track.trackIndex = 1;
        SubtitleSourceBinder binder = new SubtitleSourceBinder();
        binder.bind(Collections.singletonList(subtitle("en", "en", "English", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(format, ORIGIN_URL)));

        SelectedSubtitleSource source = binder.resolve(track);

        assertNotNull(source);
        assertEquals(ORIGIN_URL, source.getBaseUrl());
        assertEquals(SubtitleSourceBinder.Status.BOUND, binder.getStatus());
    }

    @Test
    public void rebindingDropsThePreviousSessionFormatsAndIncrementsGeneration() {
        Format firstFormat = format("en", "English");
        Format secondFormat = format("en", "English");
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        binder.bind(Collections.singletonList(subtitle("en", "en", "English", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(firstFormat, ORIGIN_URL)));
        int firstGeneration = binder.getGeneration();
        assertNotNull(binder.resolve(firstFormat));

        binder.bind(Collections.singletonList(subtitle("en", "en", "English", ORIGIN_URL)),
                Collections.singletonList(new SubtitleFormatCandidate(secondFormat, ORIGIN_URL)));

        assertEquals(firstGeneration + 1, binder.getGeneration());
        assertNull(binder.resolve(firstFormat)); // an older video response can no longer resolve
        assertEquals(SubtitleSourceBinder.Status.SOURCE_UNKNOWN, binder.getStatus());
        assertNotNull(binder.resolve(secondFormat));
    }

    @Test
    public void reportsUnboundBeforeAnyManifestWasBound() {
        SubtitleSourceBinder binder = new SubtitleSourceBinder();

        assertNull(binder.resolve(format("en", "English")));
        assertEquals(SubtitleSourceBinder.Status.UNBOUND, binder.getStatus());
        assertEquals(0, binder.getGeneration());
    }
}
