package com.liskovsoft.smartyoutubetv2.common.exoplayer.other;

import com.google.android.exoplayer2.text.Cue;
import com.liskovsoft.sharedutils.helpers.Helpers;

import java.util.ArrayList;
import java.util.List;

/**
 * Normalizes the original (untranslated) cue texts that the player renders.
 *
 * <p>This is the text handling of the former {@code SubtitleManager.forceCenterAlignment} moved
 * into its own object, without changing the result for any input the decoder can produce. The
 * timeline/prefetch code added later must share this single rule and this single incremental
 * (scrolling ASR) state instead of duplicating it.
 *
 * <p>Behavior notes carried over from the original implementation:
 * <ul>
 *     <li>Raw VTT scrolling captions arrive as repeated lines ending with {@code "\n"} or a space.
 *     Such a cue only updates the internal buffer and is not displayed; the completed line arrives
 *     afterwards as a plain cue.</li>
 *     <li>Raw TTML captions can arrive as {@code "previous\ncurrent"}; the already buffered
 *     previous line is removed and the remaining text is displayed.</li>
 *     <li>Every displayed cue is rebuilt as {@code new Cue(text)} so that the original cue is
 *     centered by the {@code SubtitleView} default positioning.</li>
 * </ul>
 *
 * <p>Null-text (image) cues have no text to normalize and are passed through unchanged. The
 * original implementation would have thrown on them; the decoder configured by this application
 * never produces them.
 */
public class OriginalSubtitleNormalizer {
    private CharSequence subsBuffer;

    /**
     * Drops the incremental scrolling state. The player must call this on video/track changes so
     * that a line buffered for the previous subtitle source cannot strip text from the next one.
     */
    public void reset() {
        subsBuffer = null;
    }

    public List<Cue> normalize(List<Cue> cues) {
        List<Cue> result = new ArrayList<>();

        if (cues == null) {
            return result;
        }

        for (Cue cue : cues) {
            if (cue == null) {
                continue;
            }

            if (cue.text == null) { // image cue: nothing to normalize
                result.add(cue);
                continue;
            }

            // Autogenerated subs repeated lines fix
            final String textStr = cue.text.toString();
            if (Helpers.endsWithAny(textStr, "\n", " ")) { // vtt subs format
                subsBuffer = textStr;
            } else if (textStr.contains("\n")) { // ttml subs format
                CharSequence text;

                if (subsBuffer != null && textStr.contains(subsBuffer)) {
                    text = textStr.replace(subsBuffer, "").replace("\n", "");
                } else {
                    text = textStr;
                }

                result.add(new Cue(text)); // sub centered by default

                String[] split = textStr.split("\n");
                subsBuffer = split.length == 2 ? split[1] : textStr;
            } else {
                CharSequence text = subsBuffer != null ? textStr.replace(subsBuffer, "") : textStr;
                result.add(new Cue(text)); // sub centered by default
                subsBuffer = text;
            }
        }

        return result;
    }
}
